version: "3.7"

services:
    app:
        image: "laratest/app:${TAG:-latest}"
        build:
            args:
                user: testusr
                uid: 1000
            context: ./
            dockerfile: application/Dockerfile
        container_name: test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./application:/var/www
        networks:
            - test-network

    web:
        image: "scout3030/web:${TAG:-latest}"
        build:
            context: ./
            dockerfile: docker-compose/nginx.dockerfile
        container_name: test-nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
            - ${SERVER_PORT_SSL:-443}:443
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
            - ./dhparam:/etc/nginx/dhparam
            - ./certbot/conf/:/etc/nginx/ssl/
            - ./certbot/data:/usr/share/nginx/html/letsencrypt
        networks:
            - test-network

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email desarrollo.jadalsoftware@gmail.com --agree-tos --no-eff-email -d migracion.jadal.pe
        volumes:
            - ./certbot/conf/:/etc/letsencrypt
            - ./certbot/logs/:/var/log/letsencrypt
            - ./certbot/data:/usr/share/nginx/html/letsencrypt
        networks:
            - test-network

    # pgsql:
    #     image: postgres:9.6
    #     container_name: test-pgsql
    #     restart: unless-stopped
    #     expose:
    #         - 5432
    #     ports:
    #         - ${DB_PORT:-5432}:5432
    #     volumes:
    #         - dbpgsql:/docker-entrypoint-initdb.d/
    #     environment:
    #         POSTGRES_USER: ${DB_USERNAME:-homestead}
    #         POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    #         POSTGRES_DB: ${DB_DATABASE:-homestead}
    #     networks:
    #         - test-network

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - ${ADMINER_PORT_DB:-8080}:8080
    #     environment:
    #         - ADMINER_DEFAULT_SERVER=pgsql
    #         - ADMINER_DESIGN=price
    #     networks:
    #         - test-network

networks:
    test-network:
        driver: bridge

volumes:
    dbpgsql:
