version: "3.7"

services:
    app:
        image: "laratest/app:${TAG:-latest}"
        build:
            args:
                user: testusr
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - test-network

    web:
        image: "scout3030/web:${TAG:-latest}"
        build:
            context: ./
            dockerfile: docker-compose/nginx.dockerfile
        container_name: test-nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
            - ${SERVER_PORT:-443}:443
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
            - ./docker-compose/dhparam:/etc/nginx/dhparam
            - ./certbot/conf/:/etc/nginx/ssl/
            - ./certbot/data:/usr/share/nginx/html/letsencrypt
        networks:
            - test-network

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email renzo.codd@gmail.com --agree-tos --no-eff-email -d migracion.jadal.pe
        volumes:
            - ./certbot/conf/:/etc/letsencrypt
            - ./certbot/logs/:/var/log/letsencrypt
            - ./certbot/data:/usr/share/nginx/html/letsencrypt

#    db:
#        image: mysql:5.7
#        container_name: test-db
#        restart: unless-stopped
#        ports:
#            - ${SERVER_PORT_DB:-3306}:3306
#        volumes:
#            - dbdata:/var/lib/mysql
#        environment:
#            - MYSQL_DATABASE=${DB_DATABASE:-homestead}
#            - MYSQL_USER=${DB_USERNAME:-homestead}
#            - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
#            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
#        networks:
#            - test-network

#    phpmyadmin:
#        image: phpmyadmin
#        restart: always
#        ports:
#           - ${PHPMYADMIN_PORT_DB:-8080}:80
#        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=${DB_HOST:-db}
#            - PMA_USER=${DB_USERNAME:-homestead}
#            - PMA_PASSWORD=${DB_PASSWORD:-secret}
#        networks:
#            - test-network

#    mailhog:
#        image: mailhog/mailhog
#        logging:
#           driver: "none"
#        ports:
#            - ${MAIL_PORT:-1025}:1025
#            - ${MAILHOG_PORT:-8025}:8025
#        networks:
#            - test-network

networks:
    test-network:
        driver: bridge

volumes:
    dbpgsql:
